---
version: 3

vars:
  KUSTOMIZE_FLAGS: --enable-helm --enable-exec --enable-alpha-plugins
  AI_PLATFORM_SERVICE_CONTAINER: teaglebuilt/ai_platform_service

tasks:
  init:
    cmds:
    - uv venv
    - uv pip install -e packages/platform_ai

  deploy:
    cmds:
    - |-
      kustomize build {{.KUSTOMIZE_FLAGS}} ./ai/k8s | kubectl apply -f -

  destroy:
    cmds:
    - |-
      kustomize build {{.KUSTOMIZE_FLAGS}} ./ai/k8s | kubectl delete -f -

  deploy_service_container:
    cmds:
    - docker build --target api -t {{.AI_PLATFORM_SERVICE_CONTAINER}}:latest .
    - docker push {{.AI_PLATFORM_SERVICE_CONTAINER}}:latest

  test-gateway:
    cmds:
    - |
      http POST {{.AI_GATEWAY_HOST}}/v1/chat/completions Content-Type:application/json x-ai-eg-model:gpt-4o-mini --raw '{
        "model": "gpt-4o-mini",
        "messages": [{
          "role": "system",
          "content": "Hello there"
        }]
      }'

  launch-dashboard:
    cmds:
    - |
      ai sync memory \
        --lance-table-path ./data/generated/lancedb/memory \
        --duckdb-path ./data/generated/analytics.db \
        --target-table memory_log
    - rill start ./data/generated/analytics.db
