---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl4ai
  namespace: ai
spec:
  selector:
    matchLabels:
      name: crawl4ai
  template:
    metadata:
      labels:
        name: crawl4ai
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: mlops-work-00
      containers:
      - name: crawl4ai
        image: unclecode/crawl4ai:basic
        ports:
        - name: http
          containerPort: 11235
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
            nvidia.com/gpu: 1
          limits:
            memory: 1Gi
            nvidia.com/gpu: 1
