---
apiVersion: v1
kind: Service
metadata:
  name: crawl4ai
  namespace: ai
spec:
  type: ClusterIP
  selector:
    name: crawl4ai
  ports:
  - port: 11235
    name: http
    targetPort: http
    protocol: TCP