---
analyze_repository_task:
  description: >
    Read all code in the repository and summarize its functionality
  expected_output: >
    A structured summary of key files and their responsibilities
  agent: repo_analyzer

write_solution_task:
  description: >
    Using the repository context and the contents of '.github/promps/objective.md', generate the code required to implement the objective
  expected_output: >
    Complete source code or patches needed to meet the objective
  agent: code_writer
  # output_file: solution.md
