research_task:
  description: >
    Conduct a thorough research about the customer and competitors in the context of {customer_domain}. Make sure you find any interesting and relevant information given the current year is 2024. We are working with them on the following project: {project_description}.
  expected_output: >
    A complete report on the customer and their customers and competitors, including their demographics, preferences, market positioning and audience engagement.
