---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: ai-gateway-routes
  namespace: ai
spec:
  schema:
    name: OpenAI
  targetRefs:
  - name: ai-platform-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  rules:
  - matches:
    - headers:
      - type: Exact
        name: x-ai-eg-model
        value: llama3:latest
    backendRefs:
    - name: ollama-backend
  - matches:
    - headers:
      - type: Exact
        name: x-ai-eg-model
        value: gpt-4o-mini
