---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com/
    version: 5.4.0
    namespace: ai
    releaseName: open-webui
    valuesFile: openwebui-values.yaml

generators:
  - secrets-generator.yaml
