---
ollama:
  enabled: true
  runtimeClassName: "nvidia"
  nodeSelector:
    kubernetes.io/hostname: mlops-work-00
  podSecurityContext:
    fsGroupChangePolicy: Always
    fsGroup: 1001
  containerSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities: { drop: ["ALL"] }
    seccompProfile: { type: RuntimeDefault }
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
      nvidia.com/gpu: 1
    limits:
      memory: 8Gi
      nvidia.com/gpu: 1
  ollama:
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
    models:
      pull:
        - llama3
        - codellama
        - llama2-uncensored
        - deepseek-r1
        - nomic-embed-text
    insecure: true

podSecurityContext:
  fsGroupChangePolicy: Always
  fsGroup: 1001
containerSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities: { drop: ["ALL"] }
  seccompProfile: { type: RuntimeDefault }
persistence:
  enabled: true
pipelines:
  enabled: true
  extraEnvVars:
    - name: DEBUG
      value: "true"
    - name: PIPELINES_URLS
      value: https://github.com/teaglebuilt/homelab/blob/main/platform/ai/pipelines/github_pipeline.py
    - name: PIPELINES_REQUIREMENTS_PATH
      value: platform/ai/pipelines
    - name: OLLAMA_HOST
      value: http://ollama.ai.svc.cluster.local:11434
    - name: N8N_API_KEY
      valueFrom:
        secretKeyRef:
          name: openwebui-secrets
          key: n8n_api_key
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: openwebui-secrets
          key: github_token

ollamaUrls: ["http://ollama.ai.svc.cluster.local:11434"]
service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: openwebui.homelab.local
    cert-manager.io/cluster-issuer: internal-ca-cluster-issuer

extraEnvVars:
  - name: WEBUI_URL
    value: https://openwebui.homelab.local
  - name: K8S_FLAG
    value: "true"
  - name: OLLAMA_HOST
    value: http://ollama.ai.svc.cluster.local:11434
  - name: OLLAMA_BASE_URL
    value: http://ollama.ai.svc.cluster.local:11434
  - name: ENABLE_RAG_WEB_SEARCH
    value: "True"
  - name: SEARXNG_QUERY_URL
    value: "http://searxng.ai.svc.cluster.local:8080/search?q=<query>"
  - name: RAG_WEB_SEARCH_ENGINE
    value: "searxng"
  - name: USE_CUDA_DOCKER
    value: "false"
  - name: ENABLE_IMAGE_GENERATION
    value: "false"
  - name: WEBUI_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: openwebui-secrets
        key: webui_secret
  - name: OPENWEBUI_API_KEY
    valueFrom:
      secretKeyRef:
        name: openwebui-secrets
        key: webui_api_key
  - name: STORAGE_PROVIDER
    value: s3
  - name: S3_REGION_NAME
    value: us-east-1
  - name: S3_KEY_PREFIX
    value: openwebui
  - name: S3_BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: aws_homelab_remote_state_backup
  - name: S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: aws_access_key_id
  - name: S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-credentials
        key: aws_secret_access_key
