---
apiVersion: v1
kind: Pod
metadata:
  name: ollama-test-connection
  namespace: ai
spec:
  nodeSelector:
    kubernetes.io/hostname: mlops-work-00
  containers:
    - name: wget
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
