---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: ollama-backend-apikey
  namespace: ai
spec:
  type: APIKey
  apiKey:
    secretRef:
      name: ollama-backend-apikey
      namespace: ai
