[tool.poetry]
name = "network_client"
version = "0.0.1"
packages = [
  { include = "*", from = "lib"}
]

[build-system]
requires = ["poetry-core", "cython<3.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.package-data]
"unifi_client" = ["unifi/models/*", "device-models.json"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "*"

[tool.poetry.group.dev.dependencies]
pytest-cov = "*"
pytest-dotenv = "*"
pytest-mock = "*"
ruff = "*"

[tool.pytest.ini_options]
addopts = "-v --cov=src --cov-report term-missing --cov-branch"
testpaths = ["tests"]
