[project]
name = "platform-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "teaglebuilt", email = "dillan.teagle.va@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
